controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController 

diff_drive_controller
        
  ros__parameters:
    left_wheel: left_wheel_joint
    right_wheel: right_wheel_joint
    wheel_separation: 0.5
    wheel_radius: 0.1
    publish_rate: 50
    enable_odom_tf: true
    odom_frame_id: odom
    base_frame_id: base_footprint
    cmd_vel_timeout: 0.5
    use_stamped_velocities: false
    enable_odom_tf: true
    odom_frame_id: odom
    base_frame_id: base_footprint