controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: "diff_drive_controller/DiffDriveController"

    joint_broad:
      type: "joint_state_broadcaster/JointStateBroadcaster"
    
diff_cont:
  ros__parameters:
    left_wheel_name: ["left_wheel_joint"]
    right_wheel_name: ["right_wheel_joint"]
    wheel_separation: 0.35
    wheel_radius: 0.05
 
    publish_rate: 30
    enable_odom_tf: true
    odom_frame_id: "odom"
    base_frame_id: "base_link"
 
    use_stamped_velocities: false
    enable_odom_tf: true